name: Child Workflow

on:
  workflow_dispatch:
    inputs:
      imageTag:
        type: string
        required: true
        description: Tag of the image for updating

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.0
      - name: Install Poetry dependencies
        working-directory: scripts
        run: |
          poetry install
      - name: Run script
        working-directory: scripts
        run: |
          poetry run python main.py --directory=/home/runner/work/argocd-test/argocd-test --app-name=nginx-app --image-tag=hello-world:latest
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update image for nginx-app
          title: Updating image for nginx-app
          base: main
          branch: updating-nginx-app
          body: |
            This PR is autogenerated by [create-pull-request](https://github.com/peter-evans/create-pull-request). 