name: Child Workflow

on:
  workflow_dispatch:
    inputs:
      imageTag:
        type: string
        required: true
        description: Tag of the image for updating

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Echo name
        shell: bash
        run: |
          pwd
